# Generated by Django 3.0.4 on 2020-03-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interval', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
