# Generated by Django 3.0.4 on 2020-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interval', '0004_auto_20200330_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
