# Generated by Django 3.0.4 on 2020-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='My_instruments',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='Short_description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='profile',
            name='Years_of_musical_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
