# Generated by Django 3.0.4 on 2020-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200326_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='My_instruments',
            new_name='my_instruments',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Short_description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Years_of_musical_experience',
            new_name='years_of_musical_experience',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
